### PR TITLE
Show status

### PR DESCRIPTION
**Pull request by zhang-arvin**
### What is changed and how it works?
ref https://github.com/database-mesh/pisanix/issues/61

What's Changed:

### Related changes
PR to update pisanix/docs/cn:
PR to update pisanix/protocol:
Need to cherry-pick to the release branch
### Check List
Tests

add show status sql parser.
add show status sql parser test case.

### CODE REVIEW

**Comment by mlycore** [comment]
Good job ! Thanks for your contribution

**Comment by xuanyuan300** [comment]
@zhang-arvin  Thanks, Please check git commit signature.

**Comment by wbtlb** [comment]
Hi @zhang-arvin 
    Thanks for your contribution.Please refer `https://github.com/database-mesh/pisanix/blob/master/CONTRIBUTING.md` to update commit message and add commit signature.

**Comment by zhang-arvin** [comment]
Submitting a branch error, I will resubmit it, the first submission, not familiar with it

**Pull request closed without merging**
